/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Diagnostic {
  level: string
  message: string
  span: any
}

export declare function minify(code: Buffer, opts: Buffer, signal?: AbortSignal | undefined | null): Promise<TransformOutput>

export declare function minifySync(code: Buffer, opts: Buffer): TransformOutput

export declare function transform(code: Buffer, opts: Buffer, signal?: AbortSignal | undefined | null): Promise<TransformOutput>

export interface TransformOutput {
  code: string
  map?: string
  errors?: Array<Diagnostic>
  /** JSON string. */
  deps?: string
  /** JSON string. */
  modulesMapping?: string
}

export declare function transformSync(code: Buffer, opts: Buffer): TransformOutput
