/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Diagnostic {
  level: string
  message: string
  span: any
}

export declare function lint(code: Buffer, opts: Buffer, signal?: AbortSignal | undefined | null): Promise<TransformOutput>

export declare function lintSync(code: Buffer, opts: Buffer): TransformOutput

export interface TransformOutput {
  errors?: Array<Diagnostic>
}
